### ISSUE TITLE
"How to use" link now 404

### ISSUE THREAD

**Issue by Hirataaaaa** [hackdaddy8000/unsuperior-ai-waifu#20]
Am i stoopid, or link/host just broken?

**Comment by MikhailChertkov** [comment]
@Hirataaaaa how did u solve the problem?

**Comment by Hirataaaaa** [comment]
> @Hirataaaaa how did u solve the problem?

It didn’t solved:)
It’s all connected to the hackdaddy’s blog site, that seems to be not hosting anymore

**Comment by Hirataaaaa** [comment]
You can copy the link and search in web archive. What I understand, that all depends on that link, for casual users ofk.

**Comment by cesarhuret** [comment]
you can also use https://real2.me/

**Comment by Hirataaaaa** [comment]
> you can also use https://real2.me/

Thanks! Site looks like a working demo, who is the author?
