### ISSUE TITLE
Automatically restart the recognizer

### ISSUE THREAD

**Issue by Kataruu** [hackdaddy8000/unsuperior-ai-waifu#6]
Hi, it's a really cool project, love it. I would like to get some help on something. I've been trying to make that when the AI is done saying its response, the recognizer start listening again. I've been messing around with the `onend` event but it always start listening again while the AI is still talking. Any ideas of what I can do? Thanks in advance!

**Comment by hackdaddy8000** [comment]
Which onend event are you referring to specifically? Can you give me a code pointer?

**Comment by Kataruu** [comment]
Nvm I found a way to do what I needed
